# Generated by Django 2.1.5 on 2019-01-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateField(default='2019-01-01'),
            preserve_default=False,
        ),
    ]
